function fvalue=f(x,y,t,nu)
% 
%fvalue(1,:)=0*ones(size(x));%sin(x);%ones(size(x));
%fvalue(2,:)=0*ones(size(x));%sin(y);%ones(size(y));
%fvalue(1,:)=(2*pi*cos(2*pi*x)+pi^2*sin(pi*x)+pi^2*sin(pi*y));
%fvalue(2,:)=(2*pi*cos(2*pi*y)-pi^3*sin(pi*x).*y);
% nu=1;
%  fvalue(1,:)=-2*nu*(x.^2+y.^2)-nu*exp(-y)+pi^2*cos(pi*x).*cos(2*pi*y);
% fvalue(2,:)=- 4*nu*x.*y-nu.*pi^3*sin(pi*x)+2*pi*(2-pi*sin(pi*x)).*sin(2*pi*y);
%  fvalue(1,:)=(1-4*nu)*ones(size(x));
% fvalue(2,:)=(1-4*nu)*ones(size(x));
fvalue(1,:)=-2*pi*sin(2*pi*t).*(x.^2.*y.^2+exp(-y))+(x.^2.*y.^2+exp(-y)).*cos(2*pi*t).*...
                2.*x.*y.^2.*cos(2*pi*t)+(-2*x.*y.^3/3+2-pi*sin(pi*x)).*cos(2*pi*t).*... 
                cos(2*pi*t).*(2*y.*x.^2 - exp(-y))...
                +pi^2*cos(2*pi*t).*cos(pi*x).*cos(2*pi*y)...
                -nu*(2*y.^2.*cos(2*pi*t)+cos(2*pi*t).*(2*x.^2 + exp(-y)));
fvalue(2,:)=-2*pi*sin(2*pi*t).*(-2*x.*y.^3/3+2-pi*sin(pi*x))+(x.^2.*y.^2+exp(-y)).*cos(2*pi*t).*...
            cos(2*pi*t).*(-(2*y.^3)/3 - pi^2*cos(x*pi))+(-2*x.*y.^3/3+2-pi*sin(pi*x)).*cos(2*pi*t).*... 
            (-2).*x.*y.^2.*cos(2*pi*t)...
            +(-2)*pi*cos(2*pi*t)*sin(2*pi*y).*(pi*sin(pi*x) - 2)...
            -nu*(pi^3*cos(2*pi*t).*sin(pi*x)-4.*x.*y*cos(2*pi*t));
% fvalue(1,:)=2*x.^3 + 4*x.^2.*y - 2*x.*y.^2 + 2*t.*x + 2*t.*y - 4*nu + 2;
% fvalue(2,:)=2*x.^2.*y + 4*x.*y.^2 + 2*t.*x - 2*y.^3 - 2*t.*y - 4*nu + 2;
end